# use known working MSYS2
os: Previous Visual Studio 2015

version: 1.0.{build}
platform: x64
clone_folder: c:\project\src\github.com\dontpanic92\wxGo
clone_depth: 5
environment:
  matrix:
  - GOROOT: c:\go17
  - GOROOT: c:\go18

build_script:
- cmd: >-

    set GOPATH=c:\project\

    set PATH=c:\msys64\mingw64\bin;%GOROOT%\bin;%PATH%

    go env

    go version

    echo %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    go get -v -t -x -tags mingw_workaround .\\...

